AWSTemplateFormatVersion: 2010-09-09
Description: |
  Roman Numerals Converter Application with Python Flask
  deployed on AWS EC2 with Cloudformation and AWS CLI
Parameters:
  KeyName:
    Description: Enter the name of your Key Pair for SSH connections
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  RomenConverter:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04cb4ca688797756f 
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref MySecGrp
      UserData: !Base64 |
          #! /bin/bash
          dnf update -y 
          dnf install python3 -y
          pip3 install flask
          dnf install pip -y
          wget https://raw.githubusercontent.com/seymamece/Roman-numerals-converter/main/roman_converter/roman-numerals-converter-app.py 
          wget -p templates https://raw.githubusercontent.com/seymamece/Roman-numerals-converter/main/roman_converter/templates/index.html
          wget -p templates https://raw.githubusercontent.com/seymamece/Roman-numerals-converter/main/roman_converter/templates/result.html
          python3 roman-numerals-converter-app.py
      Tags: 
        - Key: Name 
          Value: !Sub Seyma ${AWS::StackName} Stack
  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh and http 
      GroupName: seymasecportfolio

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Value: env
          Key: dev
  
Outputs:
  LogicalID:
    Description: Roman Numerals Converter Application URL
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt RomenConverter.PublicDnsName